(lecture01:homework1)=
# Homework 1

+ Type your name and email in the "Student details" section below.
+ Develop the code and generate the figures you need to solve the problems using this notebook.
+ For the answers that require a mathematical proof or derivation you can either:
    
    - Type the answer using the built-in latex capabilities. In this case, simply export the notebook as a pdf and upload it on gradescope; or
    - You can print the notebook (after you are done with all the code), write your answers by hand, scan, turn your response to a single pdf, and upload on gradescope.

+ The total homework points are 100. Please note that the problems are not weighed equally.

```{note}
+ This is due before the beginning of the next lecture.
+ Please match all the pages corresponding to each of the questions when you submit on gradescope.
```

## Student details

+ **First Name: Imraan**
+ **Last Name: Saleh-Esa**
+ **Email: isalehes@purdue.edu**

## Problem 1 - Python as a calculator

Use Python to evaluate the following expression:
$$
\frac{\sin(\pi/3)e^{-2}}{23^2}.
$$

In [1]:
import math
sol1 = math.sin(math.pi/3) * math.exp(-2) / (22**2)
print(sol1)


0.00024215659775055556


## Problem 2 - Python types

Find the type of the following Python variables.
You may use Python's capabilities to find the type. You don't have to guess it.

In [2]:
x = 4
print(x, type(x))

4 <class 'int'>


In [3]:
y = 23.5
print(y, type(y))

23.5 <class 'float'>


In [4]:
z = 4 / 3.1
print(z, type(z))

1.2903225806451613 <class 'float'>


In [5]:
a = (1, 2, 4)
print(a, type(a))

(1, 2, 4) <class 'tuple'>


In [6]:
b = [3, 4, 6]
print(b, type(b))

[3, 4, 6] <class 'list'>


In [7]:
c = x > 2
print(c, type(c))

True <class 'bool'>


In [8]:
d = 'Hello there!'
print(d, type(d))

Hello there! <class 'str'>


In [9]:
e = {'Name': 'Ilias Bilionis',
     'Phone number': 2106012119,
     'Zip code': 47906}
print(e, type(e))

{'Name': 'Ilias Bilionis', 'Phone number': 2106012119, 'Zip code': 47906} <class 'dict'>


In [10]:
import numpy as np
f = np.zeros((10, 4))
print(f, type(f))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>
